### ISSUE TITLE
`Promise.any(…)` should reject with an `AggregateError` instance instead of a plain array

### ISSUE THREAD

**Issue by ExE-Boss** [ungap/promise-any#1]
See https://github.com/tc39/proposal-promise-any/blob/master/README.md#why-throw-an-aggregateerror-instead-of-an-array for reasoning.

**Comment by WebReflection** [comment]
Where would the Array be stored within the object? `error.detail` ? I can't tell from that page

**Comment by ExE-Boss** [comment]
Actually, it’s `error.errors` according to the spec: https://tc39.es/proposal-promise-any/#sec-native-error-types-used-in-this-standard-aggregateerror

**Comment by WebReflection** [comment]
done in the spirit of this project, passing `{errors: array}` instead of just array

**Comment by ExE-Boss** [comment]
That object should probably also extend&nbsp;`Error`, so&nbsp;that `instanceof Error` is&nbsp;`true`.

**Comment by WebReflection** [comment]
I guess the whole point of this change was to provide an object with the expected fields instead of being just an Array. If you use a catch callback you kinda know already it's an error, right?

I am not sure it's worth it to complicate the function any further, unless there are obvious scenarios where a catch callback that should expect always errors would fail with this.

**Comment by WebReflection** [comment]
To expand a bit: the moment I provide an Error people would say it's not an AggregateError but that requires another polyfill so I am not sure it's worth the hassle
